#!/usr/bin/env python3
from ev3dev.ev3 import *
from time import sleep

mRt = LargeMotor('outB')
mLt = LargeMotor('outC')
mFlip = LargeMotor('outA')

mRt.stop()
mLt.stop()
mFlip.stop()
mFlip.run_to_rel_pos(position_sp = -80, speed_sp = 700, stop_action = "hold")
print("FORWARDS")
mRt.run_timed(time_sp = 5000, speed_sp = -1000)
mLt.run_timed(time_sp = 5000, speed_sp = -1000)
print("WAITING")
mRt.wait_while('running')
mLt.wait_while('running')
#print(" ")
#sleep(10)
#mRt.stop(stop_action="brake")
#mLt.stop(stop_action="brake")
print("BACKWARDS")
mRt.run_timed(time_sp = 5000, speed_sp = 1000)
mLt.run_timed(time_sp = 5000, speed_sp = 1000)
#mRt.stop(stop_action="brake")
#mLt.stop(stop_action="brake")
#mFlip.stop(stop_action="brake")
#print("STOPPED")
#sleep(6)